name: Yandex Mail to Telegram Notifier

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run email notifier
      env:
        YANDEX_EMAIL: ${{ secrets.YANDEX_EMAIL }}
        YANDEX_APP_PASSWORD: ${{ secrets.YANDEX_APP_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TARGET_SENDER: ${{ secrets.TARGET_SENDER }}
        TARGET_SUBJECT_KEYWORDS: ${{ secrets.TARGET_SUBJECT_KEYWORDS }}
      run: |
        python mail_notifier.py
        
    - name: Check if email_state.json exists
      id: check_state
      run: |
        if [ -f email_state.json ]; then
          echo "state_file_exists=true" >> $GITHUB_OUTPUT
        else
          echo "state_file_exists=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push if state file exists and changed
      if: steps.check_state.outputs.state_file_exists == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add email_state.json
        git diff --staged --quiet || (git commit -m "Update email state [skip ci]" && git push)
