import os
import requests

print("=== ДЕБАГ SECRETS ===")

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')

print(f"TELEGRAM_BOT_TOKEN: {TELEGRAM_BOT_TOKEN}")
print(f"TELEGRAM_CHAT_ID: {TELEGRAM_CHAT_ID}")

if not TELEGRAM_BOT_TOKEN:
    print("❌ TELEGRAM_BOT_TOKEN не установлен!")
    
if not TELEGRAM_CHAT_ID:
    print("❌ TELEGRAM_CHAT_ID не установлен!")

if TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID:
    # Проверка бота
    print("\n1. Проверка бота:")
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getMe"
    response = requests.get(url)
    print(f"   Статус: {response.status_code}")
    if response.status_code == 200:
        print("   ✅ Бот активен")
    else:
        print(f"   ❌ Ошибка бота: {response.text}")

    # Проверка отправки с текущим Chat ID
    print(f"\n2. Проверка отправки с Chat ID '{TELEGRAM_CHAT_ID}':")
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {
        'chat_id': TELEGRAM_CHAT_ID,
        'text': "Тестовое сообщение из GitHub Actions",
    }
    response = requests.post(url, json=payload)
    print(f"   Статус: {response.status_code}")
    print(f"   Ответ: {response.text}")

    if response.status_code != 200:
        print(f"\n3. Проверка доступных чатов:")
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getUpdates"
        response = requests.get(url)
        data = response.json()
        if data['ok'] and data['result']:
            print("   ✅ Доступные чаты:")
            for update in data['result']:
                if 'message' in update:
                    chat = update['message']['chat']
                    print(f"      Chat ID: {chat['id']} | Тип: {chat['type']} | Имя: {chat.get('first_name', 'N/A')}")
        else:
            print("   ❌ Чаты не найдены")
