name: Yandex Mail to Telegram Notifier

on:
  schedule:
    # Запускается каждые 5 минут
    - cron: '*/5 * * * *'
  workflow_dispatch:  # Позволяет запускать вручную из интерфейса GitHub

jobs:
  check-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run email notifier
      env:
        YANDEX_EMAIL: ${{ secrets.YANDEX_EMAIL }}
        YANDEX_APP_PASSWORD: ${{ secrets.YANDEX_APP_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TARGET_SENDER: ${{ secrets.TARGET_SENDER }}
        TARGET_SUBJECT_KEYWORDS: ${{ secrets.TARGET_SUBJECT_KEYWORDS }}
      run: |
        python mail_notifier.py
        
    - name: Commit and push if state changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add email_state.json
        git diff --staged --quiet || (git commit -m "Update email state [skip ci]" && git push)