name: Yandex Mail to Telegram Notifier

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Debug Telegram secrets
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "=== DEBUG TELEGRAM SETTINGS ==="
        echo "Bot Token starts with: ${TELEGRAM_BOT_TOKEN:0:10}..."
        echo "Chat ID: $TELEGRAM_CHAT_ID"
        
        # Test Telegram API
        python3 -c "
import os
import requests
import sys

token = os.getenv('TELEGRAM_BOT_TOKEN')
chat_id = os.getenv('TELEGRAM_CHAT_ID')

print(f'Testing with Chat ID: {chat_id}')

url = f'https://api.telegram.org/bot{token}/sendMessage'
payload = {
    'chat_id': chat_id,
    'text': 'Test from GitHub Actions'
}

response = requests.post(url, json=payload)
print(f'Status: {response.status_code}')
print(f'Response: {response.text}')

sys.exit(0 if response.status_code == 200 else 1)
        "
