name: Yandex Mail to Telegram Notifier

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Debug secrets
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python debug_secrets.py
        
    - name: Commit state file if it exists
      if: always()
      run: |
        if [ -f email_state.json ]; then
          echo "File email_state.json found, committing..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add email_state.json
          git diff --staged --quiet || (git commit -m "Update email state [skip ci]" && git push)
        else
          echo "File email_state.json not found, skipping commit"
        fi
